export MATPLOT4J_HOME=$JARPATH/matplotlib4j
export CLASSPATH=$MATPLOT4J_HOME/matplotlib4j-0.5.1.jar:$CLASSPATH
export CLASSPATH=$MATPLOT4J_HOME/guava-15.0.jar:$CLASSPATH
export CLASSPATH=$MATPLOT4J_HOME/log4j-1.2.17.jar:$CLASSPATH
export CLASSPATH=$MATPLOT4J_HOME/slf4j-api-1.7.7.jar:$CLASSPATH
export CLASSPATH=$MATPLOT4J_HOME/slf4j-log4j12-1.7.7.jar:$CLASSPATH
